### ISSUE TITLE
Unable to build to DLL

### ISSUE THREAD

**Issue by BrentKingma** [DynaSpan/MixedRealityNetworking#2]
Visual Studio doesn't want to build out the project as it is complaining about the namespace System.
Any knowledge on this subject?

**Comment by DynaSpan** [comment]
What kind of errors do you get? Are you building the right project for the right platform?

The UnityNetworking should be build for .NET whereas the UWPNetworking should be build for UWP.

**Comment by BrentKingma** [comment]
All the errors are related to the System namespace not resisting.

**Comment by DynaSpan** [comment]
Do you have some more information? I can't do much with this info.
